export const FETCH_COURSES_REQUEST = "FETCH_COURSES_REQUEST";
export const FETCH_COURSES_SUCCESS = "FETCH_COURSES_SUCCESS";
export const FETCH_COURSES_FAILURE = "FETCH_COURSES_FAILURE";

export const ENROLL_COURSE = "ENROLL_COURSE";
export const COMPLETE_COURSE = "COMPLETE_COURSE";
export const COMPLETED_COURSE_DISPLAY = "COMPLETED_COURSE_DISPLAY";
